### ISSUE TITLE
Does not work with Nylo v6

### ISSUE THREAD

**Issue by Sh1d0w** [nylo-core/laravel_auth_slate#4]
Currently it refernces not existing methods from v5

**Comment by agordn52** [comment]
Hi @Sh1d0w,

I'll take a look today 👍

**Comment by agordn52** [comment]
Hi @Sh1d0w,

In v6, you'll want to use `dart run scaffold_ui:main auth` instead of auth_slate. It'll be the new replacement.
Hope that resolves your issue.
